# Generated by Django 2.2.7 on 2019-11-30 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191130_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 0, 53, 28, 206525, tzinfo=utc)),
        ),
    ]
