# Generated by Django 2.2.7 on 2019-11-30 01:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191130_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postparagraphs',
            field=models.ManyToManyField(to='blog.PostParagraphs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 1, 6, 29, 354182, tzinfo=utc)),
        ),
    ]
