# Generated by Django 2.2.7 on 2019-11-30 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191130_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 1, 12, 53, 164189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postparagraphs',
            name='image',
            field=models.ImageField(default='static/blog/image/defaultparagraphs.jpg', upload_to='static/blog/image/'),
        ),
    ]
