# Generated by Django 2.2.7 on 2019-11-30 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191130_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 23, 34, 23, 495848, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 23, 34, 23, 499740, tzinfo=utc)),
        ),
    ]
